(source "melpa" "http://melpa.milkbox.net/packages/")
(source gnu)
(source marmalade)
(source org)

(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "cask")
(depends-on "dash")
(depends-on "deft")
(depends-on "hydra")
(depends-on "markdown-mode")
(depends-on "olivetti")
(depends-on "pallet")
(depends-on "pandoc-mode")
(depends-on "smex")
(depends-on "solarized-theme")
(depends-on "zenburn-theme")
